language: go

go:
- 1.7.3

script:
  - go get -u -v github.com/pkg/errors
  - go get -u -v github.com/stretchr/testify/assert
  - go build
  - go test -v -run="Test"  # excluding Examples, as Travis has issues
