name: go-mod-publish
on:
  push:
    tags:
      - 'v*.*.*'

# This will force a go mod to update its cache when a tag is created.

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Grab latest Tag from Git
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Debug Vars
      run: |
        echo "RELEASE_VERSION=${RELEASE_VERSION}"
        echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
        echo "https://sum.golang.org/lookup/github.com/${GITHUB_REPOSITORY}@${RELEASE_VERSION}"
    - name: Publish Tag to Go Mod
      shell: bash
      run: |
        curl https://sum.golang.org/lookup/github.com/${GITHUB_REPOSITORY}@${RELEASE_VERSION}
